version: 2

project_name: beammp-deploy

builds:
  - id: beammp-deploy
    main: .
    binary: beammp-deploy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/acm-gaming/beammp-deploy/internal/version.Version={{ .Version }}
      - -X github.com/acm-gaming/beammp-deploy/internal/version.Commit={{ .Commit }}
      - -X github.com/acm-gaming/beammp-deploy/internal/version.Date={{ .Date }}

nfpms:
  - id: linux-packages
    package_name: beammp-deploy
    formats: [deb, rpm]
    bindir: /usr/local/bin

archives:
  - formats: [tar.gz]

checksum:
  name_template: checksums.txt

